\NeedsTeXFormat{LaTeX2e} % dla pełnej jasności
\ProvidesClass{dyplom} % jedyny niezbędny element klasy :-)

\LoadClass[12pt,twoside]{mwrep} % ładujemy klasę bazową, do opcji % drukowanie 2 stronne//todo twoside vs oneside
% podanych w dokumencie dodajemy 12pt

\RequirePackage[OT4]{polski}      % odpowiednik \RequirePackage
%\RequirePackage[utf8]{inputenc} % to właściwie powinno być na zewnątrz
\RequirePackage{array,graphicx}

\RequirePackage[a4paper,left=30mm,right=15mm,top=25mm,bottom=25mm]{geometry}

\RequirePackage{tgtermes}
\RequirePackage[absolute]{textpos} % to na potrzeby strony tytułowej
\RequirePackage[table,xcdraw]{xcolor} % na potrzeby strony tytułowej i nagłówków tabel
\def\ifundefined#1{\expandafter\ifx\csname#1\endcsname\relax}
%%% Tytularia
%\renewcommand*\sectsettings{}

% Głębokość numerowania sekcji /section /subsection /subsubsection ...
\setcounter{secnumdepth}{4}

%% chapter -- pierwszy stopień
\SetSectionFormatting[breakbefore,wholewidth]{chapter}
{56\p@}
{\FormatBlockHeading{\fontsize{14pt}{14pt}\selectfont}}
{24\p@}
%% section -- drugi stopień
\SetSectionFormatting{section}
{16\p@}
{\FormatHangHeading{\fontsize{13pt}{13pt}\selectfont}}
{6\p@}
%% subsection -- ewentualny trzeci poziom
\SetSectionFormatting{subsection}
{16\p@}
{\FormatHangHeading{\fontsize{12pt}{12pt}\selectfont}}
{6\p@}
\SetSectionFormatting{subsubsection}
{16\p@}
{\FormatHangHeading{\fontsize{12pt}{12pt}\selectfont}}
{6\p@}
%%% Floaty
%% Rysunki
\renewcommand\figurename{Rysunek}
\RequirePackage{microtype}
\RequirePackage[utf8]{inputenc}
\RequirePackage[T1]{fontenc}
\RequirePackage{scrextend}
\RequirePackage{amsmath,amsfonts,amssymb,amsthm}
\RequirePackage{enumerate}
\RequirePackage[hidelinks]{hyperref}
\RequirePackage{afterpage}
\RequirePackage{multirow}
\RequirePackage{enumitem,etoolbox}
\RequirePackage{array}
\RequirePackage{float}
\RequirePackage{xstring,xifthen}
\RequirePackage{stackengine}
\RequirePackage{tikz}
\RequirePackage{arydshln}
\RequirePackage{frontpage}
%%%%%%%%%%%%%%%%%%%%%%%%%%%
\RequirePackage[titletoc,title]{appendix}

% \renewcommand{\appendixtocname}{Dodatki}
% \renewcommand{\appendixpagename}{Dodatki}
\renewcommand{\appendixname}{Dodatek}

% pakiet do składu listingów w razie potrzeby można odblokować możliwość numerowania linii lub zmienić wielkość czcionki w listingu
% na windowsie trzeba zainstalować: pip install pygments a następnie kompilacje uruchamiać z opcją: --shell-escape
\RequirePackage[cache=false]{minted}
\setminted{breaklines,
frame=lines,
framesep=5mm,
baselinestretch=1,
fontsize=\small,
linenos
}

% nowe otoczenie do składania listingów
\RequirePackage{float}
%\newfloat{listing}{!htp}{lop}
%\floatname{listing}{Kod}
\RequirePackage{chngcntr}
%\counterwithin{listing}{chapter}
\usepackage{listings}
\renewcommand\lstlistingname{Listing}
\renewcommand\lstlistlistingname{Spis kodów źródłowych}

% patch wyrównujący spis listingów do lewego marginesu
%https://tex.stackexchange.com/questions/58469/why-are-listof-and-listoffigures-styled-differently
\makeatletter
\renewcommand*{\listof}[2]{%
\@ifundefined{ext@#1}{\float@error{#1}}{%
\expandafter\let\csname l@#1\endcsname \l@figure  % <- use layout of figure
\float@listhead{#2}%
\begingroup
\setlength\parskip{0pt plus 1pt}%               % <- or drop this line completely
\@starttoc{\@nameuse{ext@#1}}%
\endgroup}}
\makeatother

\RequirePackage{url}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\pagestyle{outer} % numery stron po lewej i prawej stronie
\RequirePackage[font=normalsize, justification=centering]{caption}

\setlength{\parindent}{7mm} % wcięcie w pierwszym wierszu akapitu
\widowpenalty=1000 % żeby nagłówki nie zostawały na dole strony
\clubpenalty=1000
\hyphenpenalty=5000

\usepackage[defaultlines=4,all]{nowidow}

\textfloatsep=10pt % odstęp pommiędzy rysunkiem, tabelą, listingiem a tekstem
\renewcommand{\baselinestretch}{1} % interlinia 1

\setlength{\skip\footins}{1cm}

\setlist[itemize]{noitemsep, topsep=0pt, partopsep=0pt}
\renewcommand{\labelitemi}{$\bullet$}
\renewcommand{\labelitemii}{$\circ$}
\renewcommand{\labelitemiii}{$\circ$}
\renewcommand{\labelitemiv}{$\circ$}

\renewcommand{\arraystretch}{2}

\def\threedigits#1{%
\ifnum#1<100 0\fi
\ifnum#1<10 0\fi
\number#1}

\def\twodigits#1{%
\ifnum#1<10 0\fi
\number#1}

%https://tex.stackexchange.com/questions/120756/referencing-enumeration-items-by-number-and-name
\makeatletter
\newcommand*{\req}[1]{%
\item
\appto\@currentlabel{\textbf{ #1}}%
~#1}
\makeatother

\newcommand\capmystring[1]{\capmystringaux#1\relax}
\def\capmystringaux#1#2\relax{\uppercase{#1}#2}
\RequirePackage{truncate}
\makeatletter
\newcommand*{\atr}[2][160pt]{%
\item
\def\@currentlabel{\textbf{#2}}%
\truncate{#1}{~#2}}
\makeatother

\newcommand{\role}[1]{\emph{#1}}

\RequirePackage{bookmark}

\RequirePackage{tocloft}
\renewcommand\cftloftitlefont{\fontsize{14pt}{14pt}\bfseries}
\renewcommand\cftlottitlefont{\fontsize{14pt}{14pt}\bfseries}

%\image[source]{scale}{file path}{caption}{label}
\newcommand{\image}[5][\ownwork]{
\noindent\begin{minipage}{\textwidth}
    \begin{figure}[H]
        \centering\includegraphics[scale=#2]{#3}
        \caption{#4 \source{#1}}\label{fig:#5}
    \end{figure}
\end{minipage}
}

\newcommand{\imagewide}[4][\ownwork]{
\noindent\begin{minipage}{\textwidth}
    \begin{figure}[H]
        \centering\includegraphics[width=.85\textwidth]{#2}
        \caption{#3 \source{#1}}\label{fig:#4}
    \end{figure}
\end{minipage}
}

\newcommand{\source}[1]{(źródło: #1)}
\newcommand{\ownwork}{opr. wł.}

\newcommand{\inlinetodo}[1]{
\textcolor{red}{(#1)}
}

\newcommand{\todo}[1]{
\inlinetodo{#1}\par
}

\newcommand{\cellred}[1]{
\cellcolor[HTML]{E74C3C}\textcolor{white}{#1}
}

\newcommand{\cellgreen}[1]{
\cellcolor[HTML]{18BC9C}\textcolor{white}{#1}
}

\newcommand{\cellgray}[1]{
\cellcolor[HTML]{DDDDDD}#1
}

\makeatletter
\newcommand{\listnormal}[2]{%
\clearpage
\begingroup
\phantomsection
\addcontentsline{toc}{chapter}{#2}
\let\ps@plain\ps@normal
\pagestyle{normal}
#1
\clearpage
\endgroup}
\makeatother
\makeatletter
\newcommand\mynobreakpar{\par\nobreak\@afterheading}
\makeatother
\endinput % dla porządku
